src/Beamtime/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import include, path

from .views import (
    home_page,
    search_page,
)

urlpatterns = [
    path('chaining/', include('smart_selects.urls')), #depandant selectbox
    path('beamrequest/', include('beamrequest.urls')),
    path('admin/', admin.site.urls, name='admin'),
    path('users/', include('django.contrib.auth.urls')),
    path('', home_page, name='home'),
#    path('<str:action>/search/', search_page.as_view(), name='search_page'),
#    path('search/<str:act>/', search_page, name='search_page'),
    path('search/', search_page, name='search_page'),

#    path('search/', search_page, name='search_page'),
    path('hours/', include('hours.urls')),
    path('documentation/', include('documentation.urls')),
    path('summary/', include('summary.urls')),
   #path('login/', login_page, name='login'),
   #for debugging
   # path('__debug__/', include(debug_toolbar.urls)),

   ]

src/hours/urls.py
from django.urls import include, path

from .views import (
   hours_create_page,
   hours_home_page,
   hours_update_page,
    #hours_delete_page,
)

urlpatterns = [
   path('home/', hours_home_page, name='home'),
   path('create/', hours_create_page, name='create'),
   #path('<str:Project_Code>/detail/', hours_detail_page, name='detail'),
   path('update/', hours_update_page, name='update'),
   #path('<str:Project_Code>/delete/', hours_delete_page, name='delete'),
]

src/beamrequest/models.py
from django.db import models
from smart_selects.db_fields import ChainedForeignKey


class IonSpecies(models.Model):
#	ionspecie = models.CharField(max_length=10)
	name = models.CharField(max_length=10)

	def __str__(self):
#		return self.ionspecie
		return self.name

class Energys(models.Model):
	ion_species = models.ForeignKey(IonSpecies, on_delete=models.CASCADE)
	name = models.CharField(max_length=10)

	def __str__(self):
#		return self.energy
		return self.name

#class BeamModel(models.Model):
#	Project_Code = models.ForeignKey(BeamRequestModel, on_delete=models.CASCADE)
#	Hours = models.IntegerField(default='1')
#	Ion_Species = models.ForeignKey(IonSpecies, on_delete=models.CASCADE)
#	Energy = ChainedForeignKey(Energys, chained_field="Ion_Species", chained_model_field="Ion_Species",	show_all=False,	auto_choose=True)
#	Flux = models.CharField(max_length=50, blank = True, null = True)

#	def __str__(self):
#		return self.Name

# Create your models here.
class BeamRequestModel(models.Model):

	#status choices
	SELECT		= 'Select'
	REQUEST		= 'Request'
	TENTATIVE	= 'Tentavive'
	ACCEPTED	= 'Accepted'
	CONFIRMED	= 'Confirmed'
	CANCELLED	= 'Cancelled'
	COMPLETED	= 'Completed'
	QUEUED		= 'Queued'

	STATUS_CHOICES = [
		(SELECT, ('Select an option')),
		(REQUEST, ('Request')),
		(TENTATIVE, ('Tentative')),
		(ACCEPTED,  ('Accepted')),
		(CONFIRMED, ('Confirmed')),
		(CANCELLED, ('Cancelled')),
		(COMPLETED, ('Completed')),
		(QUEUED, ('Queued')),
	]

    #different beam choices (1 to 4)
	DIFBEAMS_CHOICES = [tuple([x,x]) for x in range(1,5)]

	#shift choices (1 to 16 is max a week)
	SHIFTS_CHOICES = [tuple([x,x]) for x in range(1,17)]

	#fields of the model
	project_code = models.CharField(unique=True, max_length=20, blank = True)
	pac_rate = models.CharField(max_length=10, blank = True)
	partrec_contact_name = models.CharField(max_length=50, blank = True)
	partrec_contact_email = models.EmailField(blank = True)
	previous_experiment = models.CharField(max_length=200, blank = True)
	status = models.CharField(max_length=25, choices=STATUS_CHOICES, default='SELECT')
	project_title = models.CharField(max_length=100, blank = True)
	spokesperson_name = models.CharField(max_length=50, blank = True)
	spokesperson_adress = models.CharField(max_length=50, blank = True)
	spokesperson_phonenumber = models.CharField(max_length=20, blank = True)
	spokesperson_email = models.EmailField(blank = True)
	collaborator_name = models.TextField(blank = True)
	collaborator_nationality = models.TextField(blank = True)
	collaborator_home_institute = models.TextField(blank = True)
	Different_Beams = models.IntegerField(choices=DIFBEAMS_CHOICES, default='1')
#	Shifts = models.IntegerField(choices=SHIFTS_CHOICES, default='1')
	beam_note = models.TextField(blank = True)
	hours_requested = models.IntegerField(default='1')
	hours_deliverd = models.PositiveIntegerField(default='0')
	ion_species = models.ForeignKey(IonSpecies, on_delete=models.CASCADE, blank = True, null=True)
	energy = ChainedForeignKey(Energys, chained_field="ion_species", chained_model_field="ion_species",	show_all=False,	auto_choose=True, blank = True, null=True)
	flux = models.CharField(max_length=50, blank = True, null = True)
	start_date = models.DateTimeField(blank = True, null=True)
	end_date = models.DateTimeField(blank = True, null=True)
	requiered_equipment = models.TextField(blank = True)
	special_requirements = models.TextField(blank = True)
	special_safety_procedures = models.TextField(blank = True)
	lab_support_requirements = models.TextField(blank = True)
	funded = models.TextField(blank = True)
	summary = models.TextField(blank = True)

	def __str__(self):
		return self.project_code

	def get_absolute_url(self):
		return f"/beamrequest/{self.project_code}"

	def get_edit_url(self):
		return f"{{self.get_absolute_url}}/update/"

	def get_delete_url(self):
#		return f"/beamrequest/{self.Project_Code}/delete/"
		return f"{{self.get_absolute_url}}/delete/"


#Ion_Species = models.ForeignKey(IonSpecies, on_delete=models.CASCADE)
#    Energy = ChainedForeignKey(Energys, chained_field="Ion_Species", chained_model_field="Ion_Species", show_all=False, auto_choose=True)

src/templates/request/create.html
<!-- request create.html -->
{% extends 'base.html' %}

{% block title %}Add Request{% endblock %}

{% load crispy_forms_tags %}

{% block extrahead %}
	
{% endblock %}



{% block content %}

	<form method="post" novalidate>
		{% csrf_token %}
		<div class="Error_Messages">
			{% for error in form.non_field_errors %}
    			{{ error }}
			{% endfor %}
		</div>

		<br><br>
		<b>Internal contact information</b>
		<hr class="divider"></hr>

		<div class="row">
			<div class="col-6">
			 {{ form.project_code|as_crispy_field }}
			</div>
			<div class="col-6">
			 {{ form.partrec_contact_name|as_crispy_field }}
			</div>
		</div>

		<div class="row">
			<div class="col-6">
			 {{ form.pac_rate|as_crispy_field }}
			</div>
			<div class="col-6">
			 {{ form.partrec_contact_email|as_crispy_field }}
			</div>
		</div>

		<div class="row">
			<div class="col-6">
			 {{ form.previous_experiment|as_crispy_field }}
			</div>
			<div class="col-6">
			 {{ form.status|as_crispy_field }}
		 </div>
		</div>


		<br><br>
		<b>External contact information</b>
		<hr class="divider"></hr>

		<div class="row justify-content-center">
		 <div class="col-6">
			{{ form.project_title|as_crispy_field }}
		 </div>
		</div>

		<div class="row">
		 <div class="col-6">
			{{ form.spokesperson_name|as_crispy_field }}
		 </div>
		 <div class="col-6">
			{{ form.spokesperson_adress|as_crispy_field }}
		 </div>
		</div>

		<div class="row">
		 <div class="col-6">
			{{ form.spokesperson_phonenumber|as_crispy_field }}
		 </div>
		 <div class="col-6">
			{{ form.spokesperson_email|as_crispy_field }}
		 </div>
		</div>
		<div class="row">
		 <div class="col-4">
			{{ form.collaborator_name|as_crispy_field }}
		 </div>
		 <div class="col-4">
			{{ form.collaborator_nationality|as_crispy_field }}
		 </div>
		 <div class="col-4">
			{{ form.collaborator_home_institute|as_crispy_field }}
		 </div>
		</div>
		 <br><br>
		 <b>Beam information</b>
		 <hr class="divider"></hr>

		<div class="row">
			<div class="col-6">
			 {{ form.start_date|as_crispy_field }}
			</div>
		    <div class="col-6">
			 {{ form.end_date|as_crispy_field }}
			</div>
		</div>
		<div class="row justify-content-center">
			<div class="col-6">
  				{{ form.Different_Beams|as_crispy_field }}
 			</div>
		</div>
		<div class="row justify-content-center">
			<!--<div id="hidden1">-->
			<div class="col-6">
	  			{{ form.ion_species|as_crispy_field }}
	  		</div>
	  		<div class="col-6">
				{{ form.energy|as_crispy_field }}
			</div>
	  		<div class="col-6">
				{{ form.flux|as_crispy_field }}
			</div>
	  		<div class="col-6">
	  		</div>
	  		<div class="col-6">
				{{ form.hours_requested|as_crispy_field }}
			</div>
	  		<div class="col-6">
				{{ form.hours_deliverd|as_crispy_field }}
			</div>
	  		<div class="col-12">
				{{ form.beam_note|as_crispy_field }}
			</div>
			<!--</div>
			<div id="hidden2">
				<div class="col-6">
	  			{#{ beam.Hours|as_crispy_field }#}
		  		{#{ beam.Ion_Species|as_crispy_field }#}
				{#{ beam.Energy|as_crispy_field }#}
				{#{ beam.Flux|as_crispy_field }#}
				</div>
			</div>
			<div id="hidden3">
				<div class="col-6">
	  			{#{ beam.Hours|as_crispy_field }#}
		  		{#{ beam.Ion_Species|as_crispy_field }#}
				{#{ beam.Energy|as_crispy_field }#}
				{#{ beam.Flux|as_crispy_field }#}
				</div>
			</div>
			<div id="hidden4">
				<div class="col-6">
	  			{#{ beam.Hours|as_crispy_field }#}
		  		{#{ beam.Ion_Species|as_crispy_field }#}
				{#{ beam.Energy|as_crispy_field }#}
				{#{ beam.Flux|as_crispy_field }#}
				</div>
			</div>-->
			<div>
				{#{ formset }#}
			</div>
		</div>
		<div class="row justify-content-center">
  		<div class="col-12">
		  {{ form.requiered_equipment|as_crispy_field }}
		  {{ form.special_requirements|as_crispy_field }}
		  {{ form.special_safety_procedures|as_crispy_field }}
		  {{ form.lab_support_requirements|as_crispy_field }}
		  {{ form.funded|as_crispy_field }}
		  {{ form.summary|as_crispy_field }}
		</div>
		</div>
		
		<div class="row justify-content-center">
			<button type="submit" class="btn btn-success">Save New Request</button>
		</div>
	</form>
<br><br><br>

<script type="text/javascript">
    $('#hidden2').css({
       'display': 'none'
    });
    $('#hidden3').css({
       'display': 'none'
    });
    $('#hidden4').css({
       'display': 'none'
    });
    $('#id_Different_Beams').on('change', function() {
       if (this.value === '2') {
           $('#hidden1').show();
           $('#hidden2').show();
           $('#hidden3').hide();
           $('#hidden4').hide();
       }
       else if ($(this).val() == '3') {
           $('#hidden1').show();
           $('#hidden2').show();
           $('#hidden3').show();
           $('#hidden4').hide();
       }
       else if ($(this).val() == '4') {
           $('#hidden1').show();
           $('#hidden2').show();
           $('#hidden3').show();
           $('#hidden4').show();
       }
       else {
           $('#hidden1').show();
           $('#hidden2').hide();
           $('#hidden3').hide();
           $('#hidden4').hide();
       }
    });
</script>
{% endblock %}

src/templates/request/delete.html
<!-- request delete.html -->
{% extends "base.html" %}


{% block content %}

<h1>Are you sure you want to delete:</h1>
<p><b>{{ object.Project_Code }}</b></p>

<form method="post">
	{% csrf_token %}
	
	<button class="btn btn-danger">Yes, Delete</button>

</form>
{% endblock %}

src/templates/request/detail.html
<!-- request detail.html -->
{% extends "base.html" %}


{% block content %}

{% for object in object_list %}

<h1>{{ object.Project_Code }}</h1>
<p>{{ object.Project_Title }}</p>


		<a href='/beamrequest/{{object.Project_Code}}/update/'>Edit</a>
		<a href='/beamrequest/{{object.Project_Code}}/delete/'>Delete</a>


{% endfor %}
{% endblock %}

src/templates/request/home.html
<!-- request home.html -->
{% extends "base.html" %}

{% block content %}
{% if user.is_authenticated %}
<p>Welcome <b>{{ user.username }}</b> what would you like to do?</p><br>
<p><a href="/beamrequest/create/" class="btn btn-success">New Request</a></p><br>
<p><a href="/search/?act=update&page=beamrequest" class="btn btn-primary">Edit Request</a></p><br>
<p><a href="/search/?act=delete" class="btn btn-danger">Delete Request</a></p><br>
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">Log In</a>
{% endif %}
{% endblock %}

src/templates/request/update.html
<!-- request update.html -->
{% extends 'base.html' %}


{% load crispy_forms_tags %}

{% block extrahead %}
	
{% endblock %}

{% block title %}{{ title }}{% endblock %}

{% block content %}

	<form method="post" novalidate>
		{% csrf_token %}
		<div class="Error_Messages">
			{% for error in form.non_field_errors %}
    			{{ error }}
			{% endfor %}
		</div>

		<br><br>

		<b>Internal contact information</b>
		<hr class="divider"></hr>

		<div class="row justify-content-center">
			<div class="col-6">
			 {{ form.project_code|as_crispy_field }}
			</div>
			<div class="col-6">
			 {{ form.partrec_contact_name|as_crispy_field }}
			</div>
		</div>

		<div class="row justify-content-center">
			<div class="col-6">
			 {{ form.pac_rate|as_crispy_field }}
			</div>
			<div class="col-6">
			 {{ form.partrec_contact_email|as_crispy_field }}
			</div>
		</div>

		<div class="row justify-content-center">
			<div class="col-6">
			 {{ form.previous_experiment|as_crispy_field }}
			</div>
			<div class="col-6">
			 {{ form.status|as_crispy_field }}
		 </div>
		</div>


		<br><br>
		<b>External contact information</b>
		<hr class="divider"></hr>

		<div class="row justify-content-center">
		 <div class="col-6">
			{{ form.project_title|as_crispy_field }}
		 </div>
		</div>

		<div class="row justify-content-center">
		 <div class="col-6">
			{{ form.spokesperson_name|as_crispy_field }}
		 </div>
		 <div class="col-6">
			{{ form.spokesperson_adress|as_crispy_field }}
		 </div>
		</div>

		<div class="row justify-content-center">
		 <div class="col-6">
			{{ form.spokesperson_phonenumber|as_crispy_field }}
		 </div>
		 <div class="col-6">
			{{ form.spokesperson_email|as_crispy_field }}
		 </div>
		</div>
		<div class="row justify-content-center">
		 <div class="col-4">
			{{ form.collaborator_name|as_crispy_field }}
		 </div>
		 <div class="col-4">
			{{ form.collaborator_nationality|as_crispy_field }}
		 </div>
		 <div class="col-4">
			{{ form.collaborator_home_institute|as_crispy_field }}
		 </div>
		</div>
		 <br><br>
		 <b>Beam information</b>
		 <hr class="divider"></hr>

		<div class="row justify-content-center">
			<div class="col-6">
			 {{ form.start_date|as_crispy_field }}
			</div>
		    <div class="col-6">
			 {{ form.end_date|as_crispy_field }}
			</div>
		</div>
		<div class="row justify-content-center">
			<div class="col-6">
  				{{ form.Different_Beams|as_crispy_field }}
 			</div>
		</div>
		<div class="row justify-content-center">
			<!--<div id="hidden1">-->
			<div class="col-6">
	  			{{ form.ion_species|as_crispy_field }}
	  		</div>
	  		<div class="col-6">
				{{ form.energy|as_crispy_field }}
			</div>
	  		<div class="col-6">
				{{ form.flux|as_crispy_field }}
			</div>
	  		<div class="col-6">
	  		</div>
	  		<div class="col-6">
				{{ form.hours_requested|as_crispy_field }}
			</div>
	  		<div class="col-6">
				{{ form.hours_deliverd|as_crispy_field }}
			</div>
	  		<div class="col-12">
				{{ form.beam_note|as_crispy_field }}
			</div>

		</div>
		<div class="row justify-content-center">
  		<div class="col-12">
		  {{ form.requiered_equipment|as_crispy_field }}
		  {{ form.special_requirements|as_crispy_field }}
		  {{ form.special_safety_procedures|as_crispy_field }}
		  {{ form.lab_support_requirements|as_crispy_field }}
		  {{ form.funded|as_crispy_field }}
		  {{ form.summary|as_crispy_field }}
		</div>
		</div>

		<div class="row justify-content-center">
			<button type="submit" class="btn btn-success">Update Request</button>
		</div>
	</form>
<br><br><br><br>

{% endblock %}